CREATE TABLE TB_SYSUSER (
    ID NUMBER(19) PRIMARY KEY,
    USERNAME VARCHAR2(50) NOT NULL UNIQUE,
    EMAIL VARCHAR2(100) NOT NULL UNIQUE,
    PASSWORD_HASH VARCHAR2(255) NOT NULL,
    FULL_NAME VARCHAR2(100) NOT NULL,
    ACTIVE NUMBER(1) DEFAULT 1 NOT NULL,
    CREATED_AT TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP NOT NULL
);

CREATE SEQUENCE TB_SYS_USER_SEQ START WITH 1 INCREMENT BY 1;

CREATE TABLE TB_SYSROLE (
    ID NUMBER(19) PRIMARY KEY,
    ROLE_CODE VARCHAR2(50) NOT NULL UNIQUE,
    ROLE_NAME VARCHAR2(100) NOT NULL
);

CREATE SEQUENCE TB_SYS_ROLE_SEQ START WITH 1 INCREMENT BY 1;

CREATE TABLE TB_SYSUSER_ROLE (
    USER_ID NUMBER(19) NOT NULL,
    ROLE_ID NUMBER(19) NOT NULL,
    CONSTRAINT PK_TB_SYS_USER_ROLE PRIMARY KEY (USER_ID, ROLE_ID),
    CONSTRAINT FK_USER_ROLE_USER FOREIGN KEY (USER_ID) REFERENCES TB_SYSUSER(ID),
    CONSTRAINT FK_USER_ROLE_ROLE FOREIGN KEY (ROLE_ID) REFERENCES TB_SYSROLE(ID)
);

CREATE TABLE TB_SYSPASSWORD_RESET_TOKEN (
    ID NUMBER(19) PRIMARY KEY,
    USER_ID NUMBER(19) NOT NULL,
    TOKEN VARCHAR2(100) NOT NULL UNIQUE,
    EXPIRES_AT TIMESTAMP NOT NULL,
    USED NUMBER(1) DEFAULT 0 NOT NULL,
    CREATED_AT TIMESTAMP NOT NULL,
    CONSTRAINT FK_RESET_TOKEN_USER FOREIGN KEY (USER_ID) REFERENCES TB_SYSUSER(ID)
);

CREATE SEQUENCE PASSWORD_RESET_TOKEN_SEQ START WITH 1 INCREMENT BY 1;

INSERT INTO TB_SYSROLE (ID, ROLE_CODE, ROLE_NAME) VALUES (TB_SYS_ROLE_SEQ.NEXTVAL, 'STAFF', 'Staff');
INSERT INTO TB_SYSROLE (ID, ROLE_CODE, ROLE_NAME) VALUES (TB_SYS_ROLE_SEQ.NEXTVAL, 'ADMIN', 'Administrator');