CREATE TABLE TB_SYSREVISION_HISTORY (
    ID NUMBER(19) PRIMARY KEY,
    MODULE_NAME VARCHAR2(100 CHAR) NOT NULL,
    ENTITY_NAME VARCHAR2(100 CHAR) NOT NULL,
    ENTITY_ID VARCHAR2(100 CHAR),
    ACTION_TYPE VARCHAR2(30 CHAR) NOT NULL,
    DESCRIPTION VARCHAR2(500 CHAR),
    PAYLOAD CLOB,
    REQUEST_PATH VARCHAR2(255 CHAR),
    CREATED_BY_USER_ID NUMBER(19),
    CREATED_BY_USERNAME VARCHAR2(100 CHAR),
    CREATED_AT TIMESTAMP NOT NULL
);

CREATE SEQUENCE TB_SYSREVISION_HISTORY_SEQ
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

CREATE INDEX IDX_IT_REV_HIS_CREATED_AT
    ON TB_SYSREVISION_HISTORY (CREATED_AT);

CREATE INDEX IDX_IT_REV_HIS_MODULE_ACT
    ON TB_SYSREVISION_HISTORY (MODULE_NAME, ACTION_TYPE);
